---
title: "WHOOP Project Statement"
output: html_notebook
---

The WHOOP wearable provides the serious athlete with a wealth of data. At the surface, it may seem simplistic in its approach; two primary metrics are provided to the user, Strain and Recovery, which show, respectively, how strenuous that particular day has been and how well the body has responded and recovered from the previous days stimulus. 

Yet, this is just the beginning. These scores are derived from underlying markers, which include:
- average heart rate
- max heart rate achieved that day
- calories burned
- sleep performance
- total time spent in bed and asleep
- total time spent in light, REM, and deep(SWS) stages of sleep
- total sleep cycles
- heart-rate variability (HRV)
- resting heart rate (RHR)
- disturbances during sleep
- sleep latency (i.e. how long it took to fall asleep)

As you can see there is a lot more than meets the eye. Personally, the return on investment I have seen in improved athletic performance, better sleep patterns and overall wellness have been amazing. 

I can now start to pinpoint the areas where I'm doing well...and the areas I'm struggling in. One of the key features for WHOOP is your ability to adapt your training to your current state. Every morning WHOOP takes the data it gathered while you slept and generates your Recovery score (which is based on markers I listed above, like HRV, RHR and sleep performance). There are three zones: green, yellow and red. If your score (which is listed as a percentage out of 100) is in the green it means that your body is primed and ready for higher amounts of strain; if it is in the yellow zone, you should proceed with caution as your body isn't in peak condition; if it is in the red zone, you should consider taking it easy that day with either some active recovery exercises or a 'rest day'. 

This information is extremely useful however the information is useful on more of a day-by-day basis. One morning you could wake up and see that your Recovery score is unexpectedly in the red zone on a day where you had a full day of training planned. 

My Springboard Mentor Jarus Singh and I started wondering: what if, with the previous information gathered from WHOOP over the past few months, we could be predict variables such as Strain, Recovery and Sleep Performance to create a longer term workout plan, say for a week? 

The benefits of this would be significant; you could plan exactly which days during the week you want to go all out, and the days where you take it a little easier to maximize performance. Additionally, it can help in terms of scheduling training around life events; after all you don't want to cut short, or even eliminate, a training session on a day where you're in the green zone and are thus leaving potential gains on the table! Instead, if you know that you're going to have a work party on Thursday, you can plan your training around that so Thursday is an active recovery/rest day and you won't have to worry about missing out on training and can fully enjoy the party! 

My initial exploratory analysis has picked up some interesting trends. Based off of these trends, I'll take a deeper dive and explore how I might be able to predict unknown values for variables such as Strain, Recovery and Sleep Performanceby utilizing a linear regression model. Based on the strength of the model, I'll continue futher by creating a training and test data set and see what the results are.

SPRINGBOARD PROJECT: SUBMIT YOUR CAPSTONE PROJECT PROPOSAL

What is the problem you want to solve?
--> Inability to plan out workouts for longer time intervals (i.e. weekly); currently only able to adapt training on a day-to-day basis based on Recovery score. 

Who is your client and why do they care about this problem? In other words, what will your client DO or DECIDE based on your analysis that they wouldn’t have otherwise?
--> My current client is Myself. However, depending on how well the model(s) can predict future variables of Strain, Recovery and Sleep Performance, this could possibly apply to fellow WHOOP users. If it displays the ability to adequately predict these variables, it would allow them to schedule their training more efficiently around life events.

What data are you going to use for this? How will you acquire this data?
--> I am going to use my own data from WHOOP. I will acquire the data via WHOOP's online platform that records the variables I listed above (see underlying markers) on a daily basis. I have created an Excel spreadsheet that has an observation for each variable for the past four months. 

In brief, outline your approach to solving this problem (knowing that this might change later).
1. Exploratory analysis utilizing ggplot package to gain a better idea of how the data looks visually
2. Review variables that showcase potential relationships and determine the correlation
3. Create linear regression models for Strain, Recovery and Sleep Performance based on markers that show correlation with these respective variables

What are your deliverables? Typically, this would include code, along with a paper and/or a slide deck.
Right now, my deliverables would be an R script with accompanying data set that walks through the process of ascertaining and testing variables and their correlations. Once a more concrete relationship has been shown, I will then try to determine how to combine these models to produce an overencompasing model that is able to show the user a daily snapshot of Strain, Recovery and Sleep Performance dependent on input via correlated biological markers that have been shown to have statistically significant effect on said variables. Lastly, I will write a detailed report of my research of the biological markers and resulting thought process that led me to create the model for predicting Strain, Recovery and Sleep performance. 



Look into later --> ROI of information based on biological markers?
